# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/joshmorgan/projects/psyne

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/joshmorgan/projects/psyne

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joshmorgan/projects/psyne/CMakeFiles /Users/joshmorgan/projects/psyne//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joshmorgan/projects/psyne/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named psyne

# Build rule for target.
psyne: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 psyne
.PHONY : psyne

# fast build rule for target.
psyne/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/build
.PHONY : psyne/fast

#=============================================================================
# Target rules for targets named simple_messaging

# Build rule for target.
simple_messaging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_messaging
.PHONY : simple_messaging

# fast build rule for target.
simple_messaging/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/simple_messaging.dir/build.make examples/CMakeFiles/simple_messaging.dir/build
.PHONY : simple_messaging/fast

#=============================================================================
# Target rules for targets named simple_messaging_zero_copy

# Build rule for target.
simple_messaging_zero_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_messaging_zero_copy
.PHONY : simple_messaging_zero_copy

# fast build rule for target.
simple_messaging_zero_copy/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/simple_messaging_zero_copy.dir/build.make examples/CMakeFiles/simple_messaging_zero_copy.dir/build
.PHONY : simple_messaging_zero_copy/fast

#=============================================================================
# Target rules for targets named producer_consumer

# Build rule for target.
producer_consumer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 producer_consumer
.PHONY : producer_consumer

# fast build rule for target.
producer_consumer/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/producer_consumer.dir/build.make examples/CMakeFiles/producer_consumer.dir/build
.PHONY : producer_consumer/fast

#=============================================================================
# Target rules for targets named multi_type_channel

# Build rule for target.
multi_type_channel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 multi_type_channel
.PHONY : multi_type_channel

# fast build rule for target.
multi_type_channel/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/multi_type_channel.dir/build.make examples/CMakeFiles/multi_type_channel.dir/build
.PHONY : multi_type_channel/fast

#=============================================================================
# Target rules for targets named zero_copy_showcase

# Build rule for target.
zero_copy_showcase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zero_copy_showcase
.PHONY : zero_copy_showcase

# fast build rule for target.
zero_copy_showcase/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/zero_copy_showcase.dir/build.make examples/CMakeFiles/zero_copy_showcase.dir/build
.PHONY : zero_copy_showcase/fast

#=============================================================================
# Target rules for targets named channel_factory_demo

# Build rule for target.
channel_factory_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 channel_factory_demo
.PHONY : channel_factory_demo

# fast build rule for target.
channel_factory_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/channel_factory_demo.dir/build.make examples/CMakeFiles/channel_factory_demo.dir/build
.PHONY : channel_factory_demo/fast

#=============================================================================
# Target rules for targets named channel_patterns_showcase

# Build rule for target.
channel_patterns_showcase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 channel_patterns_showcase
.PHONY : channel_patterns_showcase

# fast build rule for target.
channel_patterns_showcase/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/channel_patterns_showcase.dir/build.make examples/CMakeFiles/channel_patterns_showcase.dir/build
.PHONY : channel_patterns_showcase/fast

#=============================================================================
# Target rules for targets named fixed_size_demo

# Build rule for target.
fixed_size_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fixed_size_demo
.PHONY : fixed_size_demo

# fast build rule for target.
fixed_size_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/fixed_size_demo.dir/build.make examples/CMakeFiles/fixed_size_demo.dir/build
.PHONY : fixed_size_demo/fast

#=============================================================================
# Target rules for targets named dynamic_allocation_demo

# Build rule for target.
dynamic_allocation_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dynamic_allocation_demo
.PHONY : dynamic_allocation_demo

# fast build rule for target.
dynamic_allocation_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/dynamic_allocation_demo.dir/build.make examples/CMakeFiles/dynamic_allocation_demo.dir/build
.PHONY : dynamic_allocation_demo/fast

#=============================================================================
# Target rules for targets named ipc_demo

# Build rule for target.
ipc_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ipc_demo
.PHONY : ipc_demo

# fast build rule for target.
ipc_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/ipc_demo.dir/build.make examples/CMakeFiles/ipc_demo.dir/build
.PHONY : ipc_demo/fast

#=============================================================================
# Target rules for targets named ipc_producer

# Build rule for target.
ipc_producer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ipc_producer
.PHONY : ipc_producer

# fast build rule for target.
ipc_producer/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/ipc_producer.dir/build.make examples/CMakeFiles/ipc_producer.dir/build
.PHONY : ipc_producer/fast

#=============================================================================
# Target rules for targets named ipc_consumer

# Build rule for target.
ipc_consumer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ipc_consumer
.PHONY : ipc_consumer

# fast build rule for target.
ipc_consumer/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/ipc_consumer.dir/build.make examples/CMakeFiles/ipc_consumer.dir/build
.PHONY : ipc_consumer/fast

#=============================================================================
# Target rules for targets named ipc_test

# Build rule for target.
ipc_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ipc_test
.PHONY : ipc_test

# fast build rule for target.
ipc_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/ipc_test.dir/build.make examples/CMakeFiles/ipc_test.dir/build
.PHONY : ipc_test/fast

#=============================================================================
# Target rules for targets named tcp_demo

# Build rule for target.
tcp_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_demo
.PHONY : tcp_demo

# fast build rule for target.
tcp_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/tcp_demo.dir/build.make examples/CMakeFiles/tcp_demo.dir/build
.PHONY : tcp_demo/fast

#=============================================================================
# Target rules for targets named tcp_server

# Build rule for target.
tcp_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_server
.PHONY : tcp_server

# fast build rule for target.
tcp_server/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/tcp_server.dir/build.make examples/CMakeFiles/tcp_server.dir/build
.PHONY : tcp_server/fast

#=============================================================================
# Target rules for targets named tcp_client

# Build rule for target.
tcp_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_client
.PHONY : tcp_client

# fast build rule for target.
tcp_client/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/tcp_client.dir/build.make examples/CMakeFiles/tcp_client.dir/build
.PHONY : tcp_client/fast

#=============================================================================
# Target rules for targets named unix_socket_demo

# Build rule for target.
unix_socket_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unix_socket_demo
.PHONY : unix_socket_demo

# fast build rule for target.
unix_socket_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/unix_socket_demo.dir/build.make examples/CMakeFiles/unix_socket_demo.dir/build
.PHONY : unix_socket_demo/fast

#=============================================================================
# Target rules for targets named udp_multicast_demo

# Build rule for target.
udp_multicast_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 udp_multicast_demo
.PHONY : udp_multicast_demo

# fast build rule for target.
udp_multicast_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/udp_multicast_demo.dir/build.make examples/CMakeFiles/udp_multicast_demo.dir/build
.PHONY : udp_multicast_demo/fast

#=============================================================================
# Target rules for targets named websocket_demo

# Build rule for target.
websocket_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 websocket_demo
.PHONY : websocket_demo

# fast build rule for target.
websocket_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/websocket_demo.dir/build.make examples/CMakeFiles/websocket_demo.dir/build
.PHONY : websocket_demo/fast

#=============================================================================
# Target rules for targets named webrtc_demo

# Build rule for target.
webrtc_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webrtc_demo
.PHONY : webrtc_demo

# fast build rule for target.
webrtc_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/webrtc_demo.dir/build.make examples/CMakeFiles/webrtc_demo.dir/build
.PHONY : webrtc_demo/fast

#=============================================================================
# Target rules for targets named webrtc_simple_example

# Build rule for target.
webrtc_simple_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webrtc_simple_example
.PHONY : webrtc_simple_example

# fast build rule for target.
webrtc_simple_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/webrtc_simple_example.dir/build.make examples/CMakeFiles/webrtc_simple_example.dir/build
.PHONY : webrtc_simple_example/fast

#=============================================================================
# Target rules for targets named webrtc_p2p_demo

# Build rule for target.
webrtc_p2p_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webrtc_p2p_demo
.PHONY : webrtc_p2p_demo

# fast build rule for target.
webrtc_p2p_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/webrtc_p2p_demo.dir/build.make examples/CMakeFiles/webrtc_p2p_demo.dir/build
.PHONY : webrtc_p2p_demo/fast

#=============================================================================
# Target rules for targets named quic_demo

# Build rule for target.
quic_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quic_demo
.PHONY : quic_demo

# fast build rule for target.
quic_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/quic_demo.dir/build.make examples/CMakeFiles/quic_demo.dir/build
.PHONY : quic_demo/fast

#=============================================================================
# Target rules for targets named rudp_demo

# Build rule for target.
rudp_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rudp_demo
.PHONY : rudp_demo

# fast build rule for target.
rudp_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/rudp_demo.dir/build.make examples/CMakeFiles/rudp_demo.dir/build
.PHONY : rudp_demo/fast

#=============================================================================
# Target rules for targets named publish_subscribe_demo

# Build rule for target.
publish_subscribe_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 publish_subscribe_demo
.PHONY : publish_subscribe_demo

# fast build rule for target.
publish_subscribe_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/publish_subscribe_demo.dir/build.make examples/CMakeFiles/publish_subscribe_demo.dir/build
.PHONY : publish_subscribe_demo/fast

#=============================================================================
# Target rules for targets named request_reply_demo

# Build rule for target.
request_reply_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 request_reply_demo
.PHONY : request_reply_demo

# fast build rule for target.
request_reply_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/request_reply_demo.dir/build.make examples/CMakeFiles/request_reply_demo.dir/build
.PHONY : request_reply_demo/fast

#=============================================================================
# Target rules for targets named routing_demo_final

# Build rule for target.
routing_demo_final: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 routing_demo_final
.PHONY : routing_demo_final

# fast build rule for target.
routing_demo_final/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/routing_demo_final.dir/build.make examples/CMakeFiles/routing_demo_final.dir/build
.PHONY : routing_demo_final/fast

#=============================================================================
# Target rules for targets named async_messaging_demo

# Build rule for target.
async_messaging_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 async_messaging_demo
.PHONY : async_messaging_demo

# fast build rule for target.
async_messaging_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/async_messaging_demo.dir/build.make examples/CMakeFiles/async_messaging_demo.dir/build
.PHONY : async_messaging_demo/fast

#=============================================================================
# Target rules for targets named coroutine_example

# Build rule for target.
coroutine_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coroutine_example
.PHONY : coroutine_example

# fast build rule for target.
coroutine_example/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/coroutine_example.dir/build.make examples/CMakeFiles/coroutine_example.dir/build
.PHONY : coroutine_example/fast

#=============================================================================
# Target rules for targets named modern_cpp20_demo

# Build rule for target.
modern_cpp20_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 modern_cpp20_demo
.PHONY : modern_cpp20_demo

# fast build rule for target.
modern_cpp20_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/modern_cpp20_demo.dir/build.make examples/CMakeFiles/modern_cpp20_demo.dir/build
.PHONY : modern_cpp20_demo/fast

#=============================================================================
# Target rules for targets named enhanced_types_demo

# Build rule for target.
enhanced_types_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enhanced_types_demo
.PHONY : enhanced_types_demo

# fast build rule for target.
enhanced_types_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/enhanced_types_demo.dir/build.make examples/CMakeFiles/enhanced_types_demo.dir/build
.PHONY : enhanced_types_demo/fast

#=============================================================================
# Target rules for targets named message_types_demo

# Build rule for target.
message_types_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 message_types_demo
.PHONY : message_types_demo

# fast build rule for target.
message_types_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/message_types_demo.dir/build.make examples/CMakeFiles/message_types_demo.dir/build
.PHONY : message_types_demo/fast

#=============================================================================
# Target rules for targets named simple_enhanced_types_test

# Build rule for target.
simple_enhanced_types_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_enhanced_types_test
.PHONY : simple_enhanced_types_test

# fast build rule for target.
simple_enhanced_types_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/simple_enhanced_types_test.dir/build.make examples/CMakeFiles/simple_enhanced_types_test.dir/build
.PHONY : simple_enhanced_types_test/fast

#=============================================================================
# Target rules for targets named test_bytevector

# Build rule for target.
test_bytevector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bytevector
.PHONY : test_bytevector

# fast build rule for target.
test_bytevector/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_bytevector.dir/build.make examples/CMakeFiles/test_bytevector.dir/build
.PHONY : test_bytevector/fast

#=============================================================================
# Target rules for targets named test_floatvector

# Build rule for target.
test_floatvector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_floatvector
.PHONY : test_floatvector

# fast build rule for target.
test_floatvector/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_floatvector.dir/build.make examples/CMakeFiles/test_floatvector.dir/build
.PHONY : test_floatvector/fast

#=============================================================================
# Target rules for targets named performance_demo

# Build rule for target.
performance_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 performance_demo
.PHONY : performance_demo

# fast build rule for target.
performance_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/performance_demo.dir/build.make examples/CMakeFiles/performance_demo.dir/build
.PHONY : performance_demo/fast

#=============================================================================
# Target rules for targets named high_performance_messaging

# Build rule for target.
high_performance_messaging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 high_performance_messaging
.PHONY : high_performance_messaging

# fast build rule for target.
high_performance_messaging/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/high_performance_messaging.dir/build.make examples/CMakeFiles/high_performance_messaging.dir/build
.PHONY : high_performance_messaging/fast

#=============================================================================
# Target rules for targets named metrics_demo

# Build rule for target.
metrics_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 metrics_demo
.PHONY : metrics_demo

# fast build rule for target.
metrics_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/metrics_demo.dir/build.make examples/CMakeFiles/metrics_demo.dir/build
.PHONY : metrics_demo/fast

#=============================================================================
# Target rules for targets named simd_demo

# Build rule for target.
simd_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simd_demo
.PHONY : simd_demo

# fast build rule for target.
simd_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/simd_demo.dir/build.make examples/CMakeFiles/simd_demo.dir/build
.PHONY : simd_demo/fast

#=============================================================================
# Target rules for targets named custom_allocator_demo

# Build rule for target.
custom_allocator_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 custom_allocator_demo
.PHONY : custom_allocator_demo

# fast build rule for target.
custom_allocator_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/custom_allocator_demo.dir/build.make examples/CMakeFiles/custom_allocator_demo.dir/build
.PHONY : custom_allocator_demo/fast

#=============================================================================
# Target rules for targets named tensor_optimization_demo

# Build rule for target.
tensor_optimization_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tensor_optimization_demo
.PHONY : tensor_optimization_demo

# fast build rule for target.
tensor_optimization_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/tensor_optimization_demo.dir/build.make examples/CMakeFiles/tensor_optimization_demo.dir/build
.PHONY : tensor_optimization_demo/fast

#=============================================================================
# Target rules for targets named compression_demo

# Build rule for target.
compression_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compression_demo
.PHONY : compression_demo

# fast build rule for target.
compression_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/compression_demo.dir/build.make examples/CMakeFiles/compression_demo.dir/build
.PHONY : compression_demo/fast

#=============================================================================
# Target rules for targets named debug_demo

# Build rule for target.
debug_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug_demo
.PHONY : debug_demo

# fast build rule for target.
debug_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/debug_demo.dir/build.make examples/CMakeFiles/debug_demo.dir/build
.PHONY : debug_demo/fast

#=============================================================================
# Target rules for targets named debug_multicast

# Build rule for target.
debug_multicast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug_multicast
.PHONY : debug_multicast

# fast build rule for target.
debug_multicast/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/debug_multicast.dir/build.make examples/CMakeFiles/debug_multicast.dir/build
.PHONY : debug_multicast/fast

#=============================================================================
# Target rules for targets named collective_demo

# Build rule for target.
collective_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 collective_demo
.PHONY : collective_demo

# fast build rule for target.
collective_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/collective_demo.dir/build.make examples/CMakeFiles/collective_demo.dir/build
.PHONY : collective_demo/fast

#=============================================================================
# Target rules for targets named collective_simple_test

# Build rule for target.
collective_simple_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 collective_simple_test
.PHONY : collective_simple_test

# fast build rule for target.
collective_simple_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/collective_simple_test.dir/build.make examples/CMakeFiles/collective_simple_test.dir/build
.PHONY : collective_simple_test/fast

#=============================================================================
# Target rules for targets named windows_test

# Build rule for target.
windows_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 windows_test
.PHONY : windows_test

# fast build rule for target.
windows_test/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/windows_test.dir/build.make examples/CMakeFiles/windows_test.dir/build
.PHONY : windows_test/fast

#=============================================================================
# Target rules for targets named arrow_demo

# Build rule for target.
arrow_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arrow_demo
.PHONY : arrow_demo

# fast build rule for target.
arrow_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/arrow_demo.dir/build.make examples/CMakeFiles/arrow_demo.dir/build
.PHONY : arrow_demo/fast

#=============================================================================
# Target rules for targets named grpc_demo

# Build rule for target.
grpc_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grpc_demo
.PHONY : grpc_demo

# fast build rule for target.
grpc_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/grpc_demo.dir/build.make examples/CMakeFiles/grpc_demo.dir/build
.PHONY : grpc_demo/fast

#=============================================================================
# Target rules for targets named c_api_demo

# Build rule for target.
c_api_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c_api_demo
.PHONY : c_api_demo

# fast build rule for target.
c_api_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/c_api_demo.dir/build.make examples/CMakeFiles/c_api_demo.dir/build
.PHONY : c_api_demo/fast

#=============================================================================
# Target rules for targets named gpu_vector_demo

# Build rule for target.
gpu_vector_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpu_vector_demo
.PHONY : gpu_vector_demo

# fast build rule for target.
gpu_vector_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/gpu_vector_demo.dir/build.make examples/CMakeFiles/gpu_vector_demo.dir/build
.PHONY : gpu_vector_demo/fast

#=============================================================================
# Target rules for targets named vulkan_gpu_demo

# Build rule for target.
vulkan_gpu_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vulkan_gpu_demo
.PHONY : vulkan_gpu_demo

# fast build rule for target.
vulkan_gpu_demo/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/vulkan_gpu_demo.dir/build.make examples/CMakeFiles/vulkan_gpu_demo.dir/build
.PHONY : vulkan_gpu_demo/fast

src/channel/multicast_factory.o: src/channel/multicast_factory.cpp.o
.PHONY : src/channel/multicast_factory.o

# target to build an object file
src/channel/multicast_factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/multicast_factory.cpp.o
.PHONY : src/channel/multicast_factory.cpp.o

src/channel/multicast_factory.i: src/channel/multicast_factory.cpp.i
.PHONY : src/channel/multicast_factory.i

# target to preprocess a source file
src/channel/multicast_factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/multicast_factory.cpp.i
.PHONY : src/channel/multicast_factory.cpp.i

src/channel/multicast_factory.s: src/channel/multicast_factory.cpp.s
.PHONY : src/channel/multicast_factory.s

# target to generate assembly for a file
src/channel/multicast_factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/multicast_factory.cpp.s
.PHONY : src/channel/multicast_factory.cpp.s

src/channel/quic_channel.o: src/channel/quic_channel.cpp.o
.PHONY : src/channel/quic_channel.o

# target to build an object file
src/channel/quic_channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/quic_channel.cpp.o
.PHONY : src/channel/quic_channel.cpp.o

src/channel/quic_channel.i: src/channel/quic_channel.cpp.i
.PHONY : src/channel/quic_channel.i

# target to preprocess a source file
src/channel/quic_channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/quic_channel.cpp.i
.PHONY : src/channel/quic_channel.cpp.i

src/channel/quic_channel.s: src/channel/quic_channel.cpp.s
.PHONY : src/channel/quic_channel.s

# target to generate assembly for a file
src/channel/quic_channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/quic_channel.cpp.s
.PHONY : src/channel/quic_channel.cpp.s

src/channel/udp_multicast_channel.o: src/channel/udp_multicast_channel.cpp.o
.PHONY : src/channel/udp_multicast_channel.o

# target to build an object file
src/channel/udp_multicast_channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/udp_multicast_channel.cpp.o
.PHONY : src/channel/udp_multicast_channel.cpp.o

src/channel/udp_multicast_channel.i: src/channel/udp_multicast_channel.cpp.i
.PHONY : src/channel/udp_multicast_channel.i

# target to preprocess a source file
src/channel/udp_multicast_channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/udp_multicast_channel.cpp.i
.PHONY : src/channel/udp_multicast_channel.cpp.i

src/channel/udp_multicast_channel.s: src/channel/udp_multicast_channel.cpp.s
.PHONY : src/channel/udp_multicast_channel.s

# target to generate assembly for a file
src/channel/udp_multicast_channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/udp_multicast_channel.cpp.s
.PHONY : src/channel/udp_multicast_channel.cpp.s

src/channel/webrtc/ice_agent.o: src/channel/webrtc/ice_agent.cpp.o
.PHONY : src/channel/webrtc/ice_agent.o

# target to build an object file
src/channel/webrtc/ice_agent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/webrtc/ice_agent.cpp.o
.PHONY : src/channel/webrtc/ice_agent.cpp.o

src/channel/webrtc/ice_agent.i: src/channel/webrtc/ice_agent.cpp.i
.PHONY : src/channel/webrtc/ice_agent.i

# target to preprocess a source file
src/channel/webrtc/ice_agent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/webrtc/ice_agent.cpp.i
.PHONY : src/channel/webrtc/ice_agent.cpp.i

src/channel/webrtc/ice_agent.s: src/channel/webrtc/ice_agent.cpp.s
.PHONY : src/channel/webrtc/ice_agent.s

# target to generate assembly for a file
src/channel/webrtc/ice_agent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/webrtc/ice_agent.cpp.s
.PHONY : src/channel/webrtc/ice_agent.cpp.s

src/channel/webrtc_channel.o: src/channel/webrtc_channel.cpp.o
.PHONY : src/channel/webrtc_channel.o

# target to build an object file
src/channel/webrtc_channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/webrtc_channel.cpp.o
.PHONY : src/channel/webrtc_channel.cpp.o

src/channel/webrtc_channel.i: src/channel/webrtc_channel.cpp.i
.PHONY : src/channel/webrtc_channel.i

# target to preprocess a source file
src/channel/webrtc_channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/webrtc_channel.cpp.i
.PHONY : src/channel/webrtc_channel.cpp.i

src/channel/webrtc_channel.s: src/channel/webrtc_channel.cpp.s
.PHONY : src/channel/webrtc_channel.s

# target to generate assembly for a file
src/channel/webrtc_channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/channel/webrtc_channel.cpp.s
.PHONY : src/channel/webrtc_channel.cpp.s

src/compression/compression.o: src/compression/compression.cpp.o
.PHONY : src/compression/compression.o

# target to build an object file
src/compression/compression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/compression/compression.cpp.o
.PHONY : src/compression/compression.cpp.o

src/compression/compression.i: src/compression/compression.cpp.i
.PHONY : src/compression/compression.i

# target to preprocess a source file
src/compression/compression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/compression/compression.cpp.i
.PHONY : src/compression/compression.cpp.i

src/compression/compression.s: src/compression/compression.cpp.s
.PHONY : src/compression/compression.s

# target to generate assembly for a file
src/compression/compression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/compression/compression.cpp.s
.PHONY : src/compression/compression.cpp.s

src/gpu/gpu_context.o: src/gpu/gpu_context.cpp.o
.PHONY : src/gpu/gpu_context.o

# target to build an object file
src/gpu/gpu_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/gpu/gpu_context.cpp.o
.PHONY : src/gpu/gpu_context.cpp.o

src/gpu/gpu_context.i: src/gpu/gpu_context.cpp.i
.PHONY : src/gpu/gpu_context.i

# target to preprocess a source file
src/gpu/gpu_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/gpu/gpu_context.cpp.i
.PHONY : src/gpu/gpu_context.cpp.i

src/gpu/gpu_context.s: src/gpu/gpu_context.cpp.s
.PHONY : src/gpu/gpu_context.s

# target to generate assembly for a file
src/gpu/gpu_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/gpu/gpu_context.cpp.s
.PHONY : src/gpu/gpu_context.cpp.s

src/gpu/gpu_message.o: src/gpu/gpu_message.cpp.o
.PHONY : src/gpu/gpu_message.o

# target to build an object file
src/gpu/gpu_message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/gpu/gpu_message.cpp.o
.PHONY : src/gpu/gpu_message.cpp.o

src/gpu/gpu_message.i: src/gpu/gpu_message.cpp.i
.PHONY : src/gpu/gpu_message.i

# target to preprocess a source file
src/gpu/gpu_message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/gpu/gpu_message.cpp.i
.PHONY : src/gpu/gpu_message.cpp.i

src/gpu/gpu_message.s: src/gpu/gpu_message.cpp.s
.PHONY : src/gpu/gpu_message.s

# target to generate assembly for a file
src/gpu/gpu_message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/gpu/gpu_message.cpp.s
.PHONY : src/gpu/gpu_message.cpp.s

src/gpu/vulkan/vulkan_buffer.o: src/gpu/vulkan/vulkan_buffer.cpp.o
.PHONY : src/gpu/vulkan/vulkan_buffer.o

# target to build an object file
src/gpu/vulkan/vulkan_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/gpu/vulkan/vulkan_buffer.cpp.o
.PHONY : src/gpu/vulkan/vulkan_buffer.cpp.o

src/gpu/vulkan/vulkan_buffer.i: src/gpu/vulkan/vulkan_buffer.cpp.i
.PHONY : src/gpu/vulkan/vulkan_buffer.i

# target to preprocess a source file
src/gpu/vulkan/vulkan_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/gpu/vulkan/vulkan_buffer.cpp.i
.PHONY : src/gpu/vulkan/vulkan_buffer.cpp.i

src/gpu/vulkan/vulkan_buffer.s: src/gpu/vulkan/vulkan_buffer.cpp.s
.PHONY : src/gpu/vulkan/vulkan_buffer.s

# target to generate assembly for a file
src/gpu/vulkan/vulkan_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/gpu/vulkan/vulkan_buffer.cpp.s
.PHONY : src/gpu/vulkan/vulkan_buffer.cpp.s

src/memory/custom_allocator.o: src/memory/custom_allocator.cpp.o
.PHONY : src/memory/custom_allocator.o

# target to build an object file
src/memory/custom_allocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/memory/custom_allocator.cpp.o
.PHONY : src/memory/custom_allocator.cpp.o

src/memory/custom_allocator.i: src/memory/custom_allocator.cpp.i
.PHONY : src/memory/custom_allocator.i

# target to preprocess a source file
src/memory/custom_allocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/memory/custom_allocator.cpp.i
.PHONY : src/memory/custom_allocator.cpp.i

src/memory/custom_allocator.s: src/memory/custom_allocator.cpp.s
.PHONY : src/memory/custom_allocator.s

# target to generate assembly for a file
src/memory/custom_allocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/memory/custom_allocator.cpp.s
.PHONY : src/memory/custom_allocator.cpp.s

src/memory/dynamic_slab_allocator.o: src/memory/dynamic_slab_allocator.cpp.o
.PHONY : src/memory/dynamic_slab_allocator.o

# target to build an object file
src/memory/dynamic_slab_allocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/memory/dynamic_slab_allocator.cpp.o
.PHONY : src/memory/dynamic_slab_allocator.cpp.o

src/memory/dynamic_slab_allocator.i: src/memory/dynamic_slab_allocator.cpp.i
.PHONY : src/memory/dynamic_slab_allocator.i

# target to preprocess a source file
src/memory/dynamic_slab_allocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/memory/dynamic_slab_allocator.cpp.i
.PHONY : src/memory/dynamic_slab_allocator.cpp.i

src/memory/dynamic_slab_allocator.s: src/memory/dynamic_slab_allocator.cpp.s
.PHONY : src/memory/dynamic_slab_allocator.s

# target to generate assembly for a file
src/memory/dynamic_slab_allocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/memory/dynamic_slab_allocator.cpp.s
.PHONY : src/memory/dynamic_slab_allocator.cpp.s

src/psyne_minimal.o: src/psyne_minimal.cpp.o
.PHONY : src/psyne_minimal.o

# target to build an object file
src/psyne_minimal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/psyne_minimal.cpp.o
.PHONY : src/psyne_minimal.cpp.o

src/psyne_minimal.i: src/psyne_minimal.cpp.i
.PHONY : src/psyne_minimal.i

# target to preprocess a source file
src/psyne_minimal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/psyne_minimal.cpp.i
.PHONY : src/psyne_minimal.cpp.i

src/psyne_minimal.s: src/psyne_minimal.cpp.s
.PHONY : src/psyne_minimal.s

# target to generate assembly for a file
src/psyne_minimal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/psyne_minimal.cpp.s
.PHONY : src/psyne_minimal.cpp.s

src/simd/simd_ops.o: src/simd/simd_ops.cpp.o
.PHONY : src/simd/simd_ops.o

# target to build an object file
src/simd/simd_ops.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/simd/simd_ops.cpp.o
.PHONY : src/simd/simd_ops.cpp.o

src/simd/simd_ops.i: src/simd/simd_ops.cpp.i
.PHONY : src/simd/simd_ops.i

# target to preprocess a source file
src/simd/simd_ops.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/simd/simd_ops.cpp.i
.PHONY : src/simd/simd_ops.cpp.i

src/simd/simd_ops.s: src/simd/simd_ops.cpp.s
.PHONY : src/simd/simd_ops.s

# target to generate assembly for a file
src/simd/simd_ops.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/simd/simd_ops.cpp.s
.PHONY : src/simd/simd_ops.cpp.s

src/transport/quic.o: src/transport/quic.cpp.o
.PHONY : src/transport/quic.o

# target to build an object file
src/transport/quic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/transport/quic.cpp.o
.PHONY : src/transport/quic.cpp.o

src/transport/quic.i: src/transport/quic.cpp.i
.PHONY : src/transport/quic.i

# target to preprocess a source file
src/transport/quic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/transport/quic.cpp.i
.PHONY : src/transport/quic.cpp.i

src/transport/quic.s: src/transport/quic.cpp.s
.PHONY : src/transport/quic.s

# target to generate assembly for a file
src/transport/quic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psyne.dir/build.make CMakeFiles/psyne.dir/src/transport/quic.cpp.s
.PHONY : src/transport/quic.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... arrow_demo"
	@echo "... async_messaging_demo"
	@echo "... c_api_demo"
	@echo "... channel_factory_demo"
	@echo "... channel_patterns_showcase"
	@echo "... collective_demo"
	@echo "... collective_simple_test"
	@echo "... compression_demo"
	@echo "... coroutine_example"
	@echo "... custom_allocator_demo"
	@echo "... debug_demo"
	@echo "... debug_multicast"
	@echo "... dynamic_allocation_demo"
	@echo "... enhanced_types_demo"
	@echo "... fixed_size_demo"
	@echo "... gpu_vector_demo"
	@echo "... grpc_demo"
	@echo "... high_performance_messaging"
	@echo "... ipc_consumer"
	@echo "... ipc_demo"
	@echo "... ipc_producer"
	@echo "... ipc_test"
	@echo "... message_types_demo"
	@echo "... metrics_demo"
	@echo "... modern_cpp20_demo"
	@echo "... multi_type_channel"
	@echo "... performance_demo"
	@echo "... producer_consumer"
	@echo "... psyne"
	@echo "... publish_subscribe_demo"
	@echo "... quic_demo"
	@echo "... request_reply_demo"
	@echo "... routing_demo_final"
	@echo "... rudp_demo"
	@echo "... simd_demo"
	@echo "... simple_enhanced_types_test"
	@echo "... simple_messaging"
	@echo "... simple_messaging_zero_copy"
	@echo "... tcp_client"
	@echo "... tcp_demo"
	@echo "... tcp_server"
	@echo "... tensor_optimization_demo"
	@echo "... test_bytevector"
	@echo "... test_floatvector"
	@echo "... udp_multicast_demo"
	@echo "... unix_socket_demo"
	@echo "... vulkan_gpu_demo"
	@echo "... webrtc_demo"
	@echo "... webrtc_p2p_demo"
	@echo "... webrtc_simple_example"
	@echo "... websocket_demo"
	@echo "... windows_test"
	@echo "... zero_copy_showcase"
	@echo "... src/channel/multicast_factory.o"
	@echo "... src/channel/multicast_factory.i"
	@echo "... src/channel/multicast_factory.s"
	@echo "... src/channel/quic_channel.o"
	@echo "... src/channel/quic_channel.i"
	@echo "... src/channel/quic_channel.s"
	@echo "... src/channel/udp_multicast_channel.o"
	@echo "... src/channel/udp_multicast_channel.i"
	@echo "... src/channel/udp_multicast_channel.s"
	@echo "... src/channel/webrtc/ice_agent.o"
	@echo "... src/channel/webrtc/ice_agent.i"
	@echo "... src/channel/webrtc/ice_agent.s"
	@echo "... src/channel/webrtc_channel.o"
	@echo "... src/channel/webrtc_channel.i"
	@echo "... src/channel/webrtc_channel.s"
	@echo "... src/compression/compression.o"
	@echo "... src/compression/compression.i"
	@echo "... src/compression/compression.s"
	@echo "... src/gpu/gpu_context.o"
	@echo "... src/gpu/gpu_context.i"
	@echo "... src/gpu/gpu_context.s"
	@echo "... src/gpu/gpu_message.o"
	@echo "... src/gpu/gpu_message.i"
	@echo "... src/gpu/gpu_message.s"
	@echo "... src/gpu/vulkan/vulkan_buffer.o"
	@echo "... src/gpu/vulkan/vulkan_buffer.i"
	@echo "... src/gpu/vulkan/vulkan_buffer.s"
	@echo "... src/memory/custom_allocator.o"
	@echo "... src/memory/custom_allocator.i"
	@echo "... src/memory/custom_allocator.s"
	@echo "... src/memory/dynamic_slab_allocator.o"
	@echo "... src/memory/dynamic_slab_allocator.i"
	@echo "... src/memory/dynamic_slab_allocator.s"
	@echo "... src/psyne_minimal.o"
	@echo "... src/psyne_minimal.i"
	@echo "... src/psyne_minimal.s"
	@echo "... src/simd/simd_ops.o"
	@echo "... src/simd/simd_ops.i"
	@echo "... src/simd/simd_ops.s"
	@echo "... src/transport/quic.o"
	@echo "... src/transport/quic.i"
	@echo "... src/transport/quic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

