name: CI

on:
  push:
    branches: [ main, develop, v2.0.0-rc ]
  pull_request:
    branches: [ main ]

jobs:
  linux-clang:
    name: Linux Clang
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clang-version: [16, 17, 18]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Clang ${{ matrix.clang-version }}
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-${{ matrix.clang-version }} libboost-all-dev libeigen3-dev
    
    - name: Build tests
      run: |
        echo "Building tests with Clang..."
        clang++-${{ matrix.clang-version }} -std=c++20 -O3 -Wall -Wextra -pthread \
          tests/test_simple_channel.cpp -o test_simple_channel
    
    - name: Build benchmarks
      run: |
        echo "Building benchmarks with Clang..."
        clang++-${{ matrix.clang-version }} -std=c++20 -O3 -march=native -pthread \
          benchmarks/quick_all_substrates.cpp -o quick_all_substrates
    
    - name: Run tests
      run: |
        ./test_simple_channel

  macos:
    name: macOS
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: brew install eigen boost
    
    - name: Build tests
      run: |
        echo "Building tests on macOS..."
        c++ -std=c++20 -O3 -Wall -Wextra -pthread \
          tests/test_simple_channel.cpp -o test_simple_channel
    
    - name: Build benchmarks
      run: |
        echo "Building benchmarks on macOS..."
        c++ -std=c++20 -O3 -march=native -pthread \
          benchmarks/quick_all_substrates.cpp -o quick_all_substrates
    
    - name: Run tests
      run: |
        ./test_simple_channel
    
    - name: Run quick benchmarks
      run: |
        ./quick_all_substrates

  windows-msvc:
    name: Windows MSVC
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup vcpkg with cache
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'f7423ee180c4b7f40d43402c2feb3859161ef625'
    
    - name: Install dependencies via vcpkg
      run: |
        vcpkg install boost-system:x64-windows boost-thread:x64-windows boost-chrono:x64-windows eigen3:x64-windows
    
    - name: Build tests
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        echo Building Windows test with boost...
        cl /std:c++20 /O2 /EHsc /I"%VCPKG_ROOT%\installed\x64-windows\include" tests/test_windows.cpp /Fe:test_windows.exe /link /LIBPATH:"%VCPKG_ROOT%\installed\x64-windows\lib"
    
    - name: Build simple test
      shell: cmd  
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        echo Building simple channel test...
        cl /std:c++20 /O2 /EHsc /I"%VCPKG_ROOT%\installed\x64-windows\include" tests/test_simple_channel.cpp /Fe:test_simple_channel.exe /link /LIBPATH:"%VCPKG_ROOT%\installed\x64-windows\lib"
    
    - name: Run tests
      shell: cmd
      run: |
        echo Running Windows test...
        test_windows.exe
        echo.
        echo Running simple channel test...
        test_simple_channel.exe