name: Build and Test

# Only run on pushes to main and pull requests to reduce noise
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-11, clang-14]
        build_type: [Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libboost-system-dev \
            libboost-thread-dev \
            libeigen3-dev \
            libssl-dev \
            pkg-config

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DPSYNE_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure -j$(nproc)

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install \
            cmake \
            eigen \
            openssl \
            pkg-config \
            boost

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DPSYNE_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build -- -j$(sysctl -n hw.ncpu)

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure -j$(sysctl -n hw.ncpu)

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Release, Debug]
        arch: [x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Install vcpkg dependencies
        run: |
          vcpkg install eigen3:x64-windows
          vcpkg install openssl:x64-windows
          vcpkg integrate install

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
            -DPSYNE_BUILD_TESTS=ON `
            -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows `
            -A ${{ matrix.arch }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} -- /m

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure -C ${{ matrix.build_type }}

  validate-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libboost-system-dev \
            libboost-thread-dev \
            libeigen3-dev \
            libssl-dev

      - name: Build with Examples
        run: |
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DPSYNE_BUILD_EXAMPLES=ON
          cmake --build . --target psyne -j$(nproc)
