name: Release Build

# Only trigger on version tags to minimize runs
on:
  push:
    tags:
      - 'v*.*.*'

# No email notifications
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libeigen3-dev libssl-dev
        
    - name: Build Release
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        
    - name: Create Release Archive
      run: |
        cd build
        tar -czf psyne-${{ github.ref_name }}-linux.tar.gz libpsyne.so*
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/psyne-${{ github.ref_name }}-linux.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: false