name: Simple CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and run basic test
      run: |
        echo "Building simple channel test..."
        g++ -std=c++20 -O3 -pthread tests/test_simple_channel.cpp -o test_simple_channel
        echo "Running test..."
        ./test_simple_channel
        echo "✅ Channel test passed!"